version: "3.3"

services:

  algorithms:

    container_name: algorithms
    image: algorithms:latest
    restart: unless-stopped

    build:
      context: .
      dockerfile: Dockerfile

    env_file:
      - .env

    volumes:
      - .:/algorithms
