version: "3.3"

services:

  algocli:

    container_name: algocli
    image: algocli:latest
    restart: unless-stopped

    build:
      context: .
      dockerfile: Dockerfile

    env_file:
      - .env

    volumes:
      - .:/algocli
