version: "3.9"
services:
  algorithms:
    build:
      context: .
      dockerfile: Dockerfile
      shm_size: '1gb'
    image: algorithms:latest
    container_name: algorithms
    init: true
    network_mode: host
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/algorithms
